spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      group-id: user-group
#      to get without offsetting the initial values
      auto-offset-reset: earliest

server:
  port: 8081
